server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catpaw
    username: inguk
    password: 0504
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true