server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://cat-paw.cdy4cjlwhxdj.ap-northeast-2.rds.amazonaws.com/catpaw
    username: catpaw
    password: GDj3xK4XCS
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 859517757714-inv4qd0a3bplg579b4kchvfiuccfjaid.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth/code/google
            scope:
              - email
              - profile
          naver:
            provider: naver
            client-id: Egz3_CTjfumsEHwS2e9Q
            client-secret: 01Zf3stsbX
            client-name: naver-client-app
            redirect-uri: http://localhost:8080/oauth/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - email
              - profile
          kakao:
            provider: kakao
            client-id: 8b8072e57ccb00e540afb113f71878b2
            client-secret: FXhNwNZtwelcXUCv6UtUEHGm8wNlkNsP
            client-name: client-app
            redirect-uri: http://localhost:8080/oauth/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            issuer-uri: https://kauth.kakao.com
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
secret-key: vGrxHgTxbsj4QQGUWDuxpWSHKq8RQVPkashUHsuvur3oA9djvk6afij2Adnsici2nfkaz9x4sksdbij3i
token-valid-time: 18000
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://cat-paw.cdy4cjlwhxdj.ap-northeast-2.rds.amazonaws.com/catpaw
    username: catpaw
    password: GDj3xK4XCS
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false