server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://cat-paw.cdy4cjlwhxdj.ap-northeast-2.rds.amazonaws.com/catpaw
    username: catpaw
    password: GDj3xK4XCS
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true